version: '3.8'
services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.56
    container_name: jaeger-collector
    volumes:
      - ./jaeger_collector.yaml:/etc/jaeger/jaeger_collector.yaml
    command: ["--config-file=/etc/jaeger/jaeger_collector.yaml"]
    ports:
      - "14250:14250"  # OTLP gRPC receiver
      - "14268:14268"  # HTTP receiver
