receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
  jaeger:
    endpoint: "jaeger:14250"
    insecure: true
  otlp:
    endpoint: "logstash:5044"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp]
